version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: test_task_postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: akbota
      POSTGRES_PASSWORD: "4912"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U akbota -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build: .
    container_name: test_task_backend
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - docker.env
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  postgres_data: